# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

with builtins;
with lib;

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name { nativeBuildInputs = [ zig ]; } ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
      rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
    }:
    let
      parts = splitString "#" url;
      url_base = elemAt parts 0;
      url_without_query = elemAt (splitString "?" url_base) 0;
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      ...
    }@args:
    let
      parts = splitString "://" url;
      proto = elemAt parts 0;
      path = elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig (
          args
          // {
            url = "http://${path}";
          }
        );
        "git+https" = fetchGitZig (
          args
          // {
            url = "https://${path}";
          }
        );
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "raylib_zig-5.6.0-dev-KE8REGNJBQDSjjyCmf4ATVQtk_OaBpY0B7kBxwSOPEGZ";
    path = fetchZigArtifact {
      name = "raylib_zig";
      url = "git+https://github.com/raylib-zig/raylib-zig?ref=devel#163b1ef2e993fe7cc7c76bb3213d98612f4b7676";
      hash = "sha256-lvwlqHjliuezvcDN74k1p/4Ynpgq70SQDlc7HMZwvt4=";
      rev = "163b1ef2e993fe7cc7c76bb3213d98612f4b7676";
    };
  }
  {
    name = "raylib-5.6.0-dev-whq8uCg2ywTzCiX3VEP9RuCMXR6_VnDBmkj8GjL_p5QN";
    path = fetchZigArtifact {
      name = "raylib";
      url = "git+https://github.com/raysan5/raylib#8ada37d9671682f420a2be1f1afd4b06173b81ad";
      hash = "sha256-Ay4EAwfQZeH+C3QE54iqjGy6SZBIrTy32XmUvg0zNCE=";
      rev = "8ada37d9671682f420a2be1f1afd4b06173b81ad";
    };
  }
  {
    name = "N-V-__8AABHMqAWYuRdIlflwi8gksPnlUMQBiSxAqQAAZFms";
    path = fetchZigArtifact {
      name = "xcode_frameworks";
      url = "git+https://github.com/hexops/xcode-frameworks#9a45f3ac977fd25dff77e58c6de1870b6808c4a7";
      hash = "sha256-xveFYoQu0BT+ZtEsyca/zdQ/so9jPK56SeX3xmF3iro=";
      rev = "9a45f3ac977fd25dff77e58c6de1870b6808c4a7";
    };
  }
  {
    name = "N-V-__8AAJl1DwBezhYo_VE6f53mPVm00R-Fk28NPW7P14EQ";
    path = fetchZigArtifact {
      name = "emsdk";
      url = "git+https://github.com/emscripten-core/emsdk#4.0.9";
      hash = "sha256-ftUQjgMio8G3aHIux9ZckJFYq1Vdfkv5w3830XO1Ris=";
      rev = "3bcf1dcd01f040f370e10fe673a092d9ed79ebb5";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqApRAACspTbAZnuNKWIzfWzSYgYkb2nWAXZ-tqqt";
    path = fetchZigArtifact {
      name = "zemscripten";
      url = "git+https://github.com/zig-gamedev/zemscripten#3fa4b778852226c7346bdcc3c1486e875a9a6d02";
      hash = "sha256-g/sHkcp+zdJEEAaooCS4joPGSij57RVKoLCcef0aRIE=";
      rev = "3fa4b778852226c7346bdcc3c1486e875a9a6d02";
    };
  }
  {
    name = "N-V-__8AALUbbwDKkSH4nbf3Ml_dTWo9qbELvle5i9eQZMuo";
    path = fetchZigArtifact {
      name = "raygui";
      url = "git+https://github.com/raysan5/raygui#9cdfec460b43a17264af3c181c46f62bf107ac17";
      hash = "sha256-Xhx4hX9S+L3/yF7UIJMv5/v4ftu9I/1JrlzK2XVmYVw=";
      rev = "9cdfec460b43a17264af3c181c46f62bf107ac17";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqFJSAAB8hgnRt5DDMKP3zLlDtMnUDwYRJVCa5lGY";
    path = fetchZigArtifact {
      name = "zemscripten";
      url = "git+https://github.com/zig-gamedev/zemscripten?ref=main#00da03b188220374a57cb34cda6230b8d53737ea";
      hash = "sha256-tbZ5bA2Tz4hxSwO1bqHkGkZZtrSP0S7ezOWzcH7wqpw=";
      rev = "00da03b188220374a57cb34cda6230b8d53737ea";
    };
  }
  {
    name = "zerl-0.2.0-92d69iiJAADbGHYQVaOgEnjZb2QlM6yaHmPgxgl3AdMq";
    path = fetchZigArtifact {
      name = "zerl";
      url = "git+https://github.com/dont-rely-on-nulls/zerl?ref=zig-0.15#0fd0d8e3a0105cfc0620ea88f43e6584b89723e3";
      hash = "sha256-A8P/jmkiPWgZ/ucAJQOpysPYt5zgk81dCv2B9kwhwBk=";
      rev = "0fd0d8e3a0105cfc0620ea88f43e6584b89723e3";
    };
  }
]
