# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

with builtins;
with lib;

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name { nativeBuildInputs = [ zig ]; } ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
      rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
    }:
    let
      parts = splitString "#" url;
      url_base = elemAt parts 0;
      url_without_query = elemAt (splitString "?" url_base) 0;
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      ...
    }@args:
    let
      parts = splitString "://" url;
      proto = elemAt parts 0;
      path = elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig (
          args
          // {
            url = "http://${path}";
          }
        );
        "git+https" = fetchGitZig (
          args
          // {
            url = "https://${path}";
          }
        );
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "raylib_zig-5.6.0-dev-KE8REBMyBQCnQ9RBhHsoSKr97XmDHF84wx3g0UiMRDxj";
    path = fetchZigArtifact {
      name = "raylib_zig";
      url = "https://github.com/Not-Nik/raylib-zig/archive/d6c77762cbdebbf56d3ff101142048dfae2496c4.tar.gz";
      hash = "sha256-U/7W7ZBEkV1TQLCQg7ruEX4vH453Saijry2+35c820U=";
    };
  }
  {
    name = "raylib-5.5.0-whq8uFV0zQA9NXxhpYFZk_yHW6xzg5eKGmOtMJ2DOTdU";
    path = fetchZigArtifact {
      name = "raylib";
      url = "git+https://github.com/raysan5/raylib?ref=master#f5c96302d5623950dccdca31f8dd66d6d633dbd1";
      hash = "sha256-hYMxc1c10gKtGlvcQMOyfJaXPQ+WlgPfPedhJjOxnFM=";
      rev = "f5c96302d5623950dccdca31f8dd66d6d633dbd1";
    };
  }
  {
    name = "N-V-__8AABHMqAWYuRdIlflwi8gksPnlUMQBiSxAqQAAZFms";
    path = fetchZigArtifact {
      name = "xcode_frameworks";
      url = "git+https://github.com/hexops/xcode-frameworks#9a45f3ac977fd25dff77e58c6de1870b6808c4a7";
      hash = "sha256-xveFYoQu0BT+ZtEsyca/zdQ/so9jPK56SeX3xmF3iro=";
      rev = "9a45f3ac977fd25dff77e58c6de1870b6808c4a7";
    };
  }
  {
    name = "N-V-__8AALRTBQDo_pUJ8IQ-XiIyYwDKQVwnr7-7o5kvPDGE";
    path = fetchZigArtifact {
      name = "emsdk";
      url = "git+https://github.com/emscripten-core/emsdk#3.1.50";
      hash = "sha256-YUwb8yfz26Tfz4wyN13MBsdyA40ygJwfxHWt4eFMvQE=";
      rev = "e2627e265d940db5ea58dffa63e490375bfc92e5";
    };
  }
  {
    name = "N-V-__8AAEp9UgBJ2n1eks3_3YZk3GCO1XOENazWaCO7ggM2";
    path = fetchZigArtifact {
      name = "raygui";
      url = "git+https://github.com/raysan5/raygui#1536ae35c7b42d863135f4181fd2a225e531f68b";
      hash = "sha256-p33HJcYZuaUV1w4iUqcfNj/mtB1ULcdBI0+pK0U0t3E=";
      rev = "1536ae35c7b42d863135f4181fd2a225e531f68b";
    };
  }
  {
    name = "zerl-0.2.0-92d69riJAACsO0D--Mak2AqKRzeUHEQlBa2kLi1B1eoY";
    path = fetchZigArtifact {
      name = "zerl";
      url = "https://github.com/dont-rely-on-nulls/zerl/archive/refs/tags/v0.2.0.tar.gz";
      hash = "sha256-ZbIv1T/WGnGMlYj3cO5Mdj6RoXIYiQN3tkGOGAaAFTg=";
    };
  }
]
