# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    pure_migrations = builder {
      name = "pure_migrations";
      version = "1.3.0";
      src = fetchHex {
        pkg = "pure_migrations";
        version = "1.3.0";
        sha256 = "sha256-ACad4KGpu+G3aB7B8/pZ7p2AgVgiJqlMYz5vlLXIi8M=";
      };
      beamDeps = [ ];
    };
    pc = builder {
      name = "pc";
      version = "1.15.0";
      src = fetchHex {
        pkg = "pc";
        version = "1.15.0";
        sha256 = "sha256-TA+tT2Q3yuNT1RfaIY/ng0e4/6RLmBeIdJTKquVFlbM=";
      };
      beamDeps = [ ];
    };
    erlandono = builder {
      name = "erlandono";
      version = "3.1.3";
      src = fetchHex {
        pkg = "erlandono";
        version = "3.1.3";
        sha256 = "sha256-K/yvZZwAMsW1zv1ILrvbohqyAdFXmlRIXgkZX8IJJXc=";
      };
      beamDeps = [ ];
    };
    erlando = builder {
      name = "erlando";
      version = "3.1.1";
      src = fetchHex {
        pkg = "erlando";
        version = "3.1.1";
        sha256 = "sha256-ljPLSXjb14gn+nbqTDsL0kz71N2a9ICI6SLnEVSUo0Q=";
      };
      beamDeps = [ ];
    };
    epgsql = builder {
      name = "epgsql";
      version = "4.7.1";
      src = fetchHex {
        pkg = "epgsql";
        version = "4.7.1";
        sha256 = "sha256-tthrfcQshVWx1OIIgOUJnW1tBTFIAA4YjlSPmOTgGDY=";
      };
      beamDeps = [ ];
    };
    csv = builder {
      name = "csv";
      version = "3.0.3";
      src = fetchHex {
        pkg = "csve";
        version = "3.0.3";
        sha256 = "sha256-dB0aVaq62qPg/hMFEFAQGnPpDEVwuflAOpOdlUaBNSE=";
      };
      beamDeps = [ pc ];
    };
  };
in self
