# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    pc = builder {
      name = "pc";
      version = "1.15.0";
      src = fetchHex {
        pkg = "pc";
        version = "1.15.0";
        sha256 = "sha256-TA+tT2Q3yuNT1RfaIY/ng0e4/6RLmBeIdJTKquVFlbM=";
      };
      beamDeps = [ ];
    };
    migraterl = builder {
      name = "migraterl";
      version = "0.1.0";
      src = fetchHex {
        pkg = "migraterl";
        version = "0.1.0";
        sha256 = "sha256-XoA42crAux0VyHtT8Ubdx5Pat72/GLFlHb98PCaBuwM=";
      };
      beamDeps = [ epgsql erlandono ];
    };
    erlandono = builder {
      name = "erlandono";
      version = "3.1.3";
      src = fetchHex {
        pkg = "erlandono";
        version = "3.1.3";
        sha256 = "sha256-K/yvZZwAMsW1zv1ILrvbohqyAdFXmlRIXgkZX8IJJXc=";
      };
      beamDeps = [ ];
    };
    epgsql = builder {
      name = "epgsql";
      version = "4.7.1";
      src = fetchHex {
        pkg = "epgsql";
        version = "4.7.1";
        sha256 = "sha256-tthrfcQshVWx1OIIgOUJnW1tBTFIAA4YjlSPmOTgGDY=";
      };
      beamDeps = [ ];
    };
    csv = builder {
      name = "csv";
      version = "3.0.3";
      src = fetchHex {
        pkg = "csve";
        version = "3.0.3";
        sha256 = "sha256-dB0aVaq62qPg/hMFEFAQGnPpDEVwuflAOpOdlUaBNSE=";
      };
      beamDeps = [ pc ];
    };
  };
in self
