name: "[Server] Build"

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - server/**
      - flake.nix
      - flake.lock
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - server/**
      - flake.nix
      - flake.lock

permissions:
  contents: read

env:
  PGHOST: localhost
  PGPORT: 5432
  PGPASSWORD: admin
  PGUSER: admin
  PGDATABASE: mmo

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-bookworm
        env:
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_DB: ${{ env.PGDATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      # To leverage devenv inside Github Actions
      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      # Actual Pipelines
      - name: "[Server] Build"
        run: |
          nix build .#server

      - name: "[Server] Tests"
        run: |
          nix develop .#ci --impure -c just test

