name: "[Server] Dialyzer"

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - server/**
      - flake.nix
      - flake.lock
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - server/**
      - flake.nix
      - flake.lock

permissions:
  contents: read

jobs:
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: "[Server] Build"
        run: |
          nix develop .#ci --impure -c just build

      - name: "[Server] Check Dialyzer"
        continue-on-error: true
        run: |
          nix develop .#ci --impure -c just d
