name: Update flake.lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # At 00:00 on the first day of each month
    - cron: '0 0 1 * *'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automation
